apiVersion: v1
kind: Service
metadata:
    name: web
spec:
    ports:
        -   port: 9000
            targetPort: 9000
            protocol: TCP
            name: http
    selector:
        app: fpm

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: fpm
spec:
    replicas: 1
    selector:
        matchLabels:
            app: fpm
    template:
        metadata:
            labels:
                app: fpm
        spec:
            containers:
                -   name: fpm
                    image: docker.pkg.github.com/qwertys318/keep-the-only-chance/ktoc-fpm:latest
                    ports: [{containerPort: 9000}]
                    volumeMounts:
                        -   name: env
                            mountPath: /var/www/html/env
                    command:
                        - sh
                        - -c
                        - |
                          cp ./env/.env ./
                          composer dump-env prod
                          php-fpm
            imagePullSecrets:
                -   name: github-registry
            volumes:
                -   name: env
                    secret:
                        secretName: env
