parameters:
    env: '%env(APP_ENV)%'
    siteName: '%env(SITE_NAME)%'
    domain: '%env(DOMAIN)%'
    web3_provider: '%env(WEB3_PROVIDER)%'
    keep_bonding_address: '%env(KEEP_BONDING_ADDRESS)%'
    version: '%env(APP_VERSION)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Controller\IndexController:
        tags: ['controller.service_arguments']
        calls: [[setContainer, ['@service_container']]]
        arguments:
            - '%siteName%'
            - '%domain%'
